### ISSUE TITLE
How Script vs-extension works?

### ISSUE THREAD

**Issue by javierarocena** [nurmohammed840/achievement#3]
Sorry, I'm completely lost.

How can I run thats script?

Using node (node .vscode/main.js)?
npm scripts?
vscode run its automatic?

Thanks!

**Comment by nurmohammed840** [comment]
1. Create a folder named `.vscode` in your workspace
2. Create a file named `.vscode/main.js`
3. Reload window. Press `f1` type `>Developer: Reload Window`

Example : 
```js
// {YourWorkSpaceFolder}/.vscode/main.js
window.showInformationMessage('Hello World!');
```
Vscode will run your script automatic.But you need to `Reload window` after any change you made in your JS/TS file. 
Feel Free To Ask Anything...

**Comment by javierarocena** [comment]
Thanks for your quick answer!

Still not working... what I'm doing wrong?

![image](https://user-images.githubusercontent.com/33159867/102825606-65d29680-43df-11eb-8e6d-bab63f1c0318.png)

![image](https://user-images.githubusercontent.com/33159867/102825581-53f0f380-43df-11eb-820b-76bef667ced7.png)

![image](https://user-images.githubusercontent.com/33159867/102825694-9286ae00-43df-11eb-80b7-8ccbde596f24.png)

**Comment by nurmohammed840** [comment]
Hmm...Does `Script` Extension running ? Is there any word called 'Script' in your `Status Bar` ? 
Try this... Uninstall this extension. then reinstall it. (may require, Reload window)

One more thing... Are you using mac or Linux ?

**Comment by nurmohammed840** [comment]
You did good!
 
Maybe,For some reason `Script` extension could't resolve your script `main.js` file...
Like Sometime `{workspace}/.vscode` folder is not the correct folder.It can be  located in deferent path( If you change it manually ).

To confirm it . goto : `>Preferences: Open Workspace Settings (JSON)` It will redirect your original `.vscode` folder.

Or Maybe its because deferent OS.If so, then I will fix it soon!  ; - )

**Comment by nurmohammed840** [comment]
Hey! Please upgrade to v0.0.7 and  Please kindly  inform  me if your issue is resolved!

**Comment by javierarocena** [comment]
Its works after updating!! I was using mac.

Thanks :)
