### ISSUE TITLE
Support : Syntax highlighting for C/C++

### ISSUE THREAD

**Issue by mate329** [nurmohammed840/achievement#4]
Hi!
I have a problem with syntax highlighting for C/C++ programs but for every other programming languages it works. I’ve reinstalled VSC, deleted every other extension and reinstalled the theme and still no progress. Could you help me?

Thank you in advance!

**Comment by nurmohammed840** [comment]
Actually this is all in one pack only for  JavaScript, Typescript. In this pack, theme ( JustBlack ) + highlighter ( code , regex, type , xml , etc...)  

So If you just want for Theme. This is not a good extension for C / C++. Because Syntax highlighting only supported for JavaScript. Sorry, I should publish a version only for Theme and one for Highlighting.

But If you like theme (JustBlack) . Fork this repo . modify syntax highlighting text-mate  rule for C/C++.  also publish the work to the world.
